### ISSUE TITLE
Document why/how it's better

### ISSUE THREAD

**Issue by dblock** [EmCousin/grape_fast_jsonapi#3]
Maybe some performance benchmarks?

**Comment by EmCousin** [comment]
@dblock sorry for the - very - late answer on that matter. I'm not sure how a performance benchmark would be relevant here, since this gem is supposed to be only a bridge between Grape and fast_jsonapi. The performance benchmarks are already well described on [their docs](https://github.com/Netflix/fast_jsonapi). Unless I'm missing the point and you're actually talking about something else?

**Comment by EmCousin** [comment]
Closing, feel free to reopen with new insights
